
name: Continuous integration

on:
    push:
    pull_request:

jobs:
    check:
        name: Run all checks
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install Dependencies
              run: |
                  sudo apt-get update
                  sudo make build-dep
            - name: Run CI tests
              run: make test
