
name: CI

on: [push]

jobs:
    check:
        name: Run all tests and builds
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install Dependencies
              run: |
                  sudo apt-get update
                  sudo make build-dep
                  sudo apt-get install -y gnuplot
            - name: Run CI tests
              run: make test
            - name: Create report pages
              run: |
                  make pages
                  make pages/stats.pdf
