
name: CI

on: [push]

jobs:
    check:
        name: Run all tests and builds
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install Dependencies
              run: sudo make build-dep
            - name: Install graphing tools
              run: sudo apt-get install -y gnuplot
            - name: Run CI tests
              run: make test
            - name: Create report pages
              run: make pages
            - name: Create report graphs
              run: make pages/stats.pdf
